services:
  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    restart: unless-stopped
    env_file:
      - ${OPS_ROOT:-../../../}/etc/global.env
      - ${OPS_ROOT:-../../../}/etc/srv/foundation.headscale.env
    volumes:
      - ${OPS_ROOT:-../../../}/lib/headscale:/var/lib/headscale
      - ${OPS_ROOT:-../../../}/srv/foundation/headscale/config:/etc/headscale:ro
    networks:
      - net_internal
    labels:
      - caddy=${HEADSCALE_HOST}
      - caddy.reverse_proxy=headscale:8080

networks:
  net_internal:
    external: true
    name: net_internal
