services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    env_file:
      - ${OPS_ROOT:-../../../}/etc/global.env
      - ${OPS_ROOT:-../../../}/etc/srv/apps.n8n.env
    volumes:
      - ${OPS_ROOT:-../../../}/lib/n8n:/home/node/.n8n
    networks: [net_internal]
    labels:
      - caddy=${N8N_HOST}
      - caddy.reverse_proxy=n8n:5678

networks:
  net_internal:
    external: true
    name: net_internal
