services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    env_file:
      - ${OPS_ROOT:-../../../}/etc/global.env
      - ${OPS_ROOT:-../../../}/etc/srv/apps.n8n.env
    volumes:
      - ${OPS_ROOT:-../../../}/lib/n8n:/home/node/.n8n
    networks: [net_internal]
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${N8N_HOST}`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls.certresolver=le-dns
      - traefik.http.services.n8n.loadbalancer.server.port=5678

networks:
  net_internal:
    external: true
    name: net_internal
