services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    env_file:
      - ${OPS_ROOT:-../../../}/etc/global.env
      - ${OPS_ROOT:-../../../}/etc/srv/apps.portainer.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${OPS_ROOT:-../../../}/lib/portainer:/data
    networks: [net_internal]
    labels:
      - caddy=${PORTAINER_HOST}
      - caddy.reverse_proxy=portainer:9000

networks:
  net_internal:
    external: true
    name: net_internal
