services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    env_file:
      - ${OPS_ROOT:-../../../}/etc/global.env
    command:
      - --configfile=/config/traefik.yml
    ports:
      - "80:80"
      - "443:443"
      - "8880:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${OPS_ROOT:-../../../}/lib/traefik:/data
      - ${OPS_ROOT:-../../../}/lib/certs:/certs:ro
      - ${OPS_ROOT:-../../../}/srv/edge/traefik/config:/config:ro
    networks:
      - net_external
      - net_internal

networks:
  net_external:
    external: true
    name: net_external
  net_internal:
    external: true
    name: net_internal

