services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - ${OPS_ROOT:-../../../}/etc/global.env
      - ${OPS_ROOT:-../../../}/etc/srv/apps.vaultwarden.env
    volumes:
      - ${OPS_ROOT:-../../../}/lib/vaultwarden:/data
    networks: [net_internal]
    labels:
      - caddy=${VAULT_HOST}
      - caddy.reverse_proxy=vaultwarden:80

networks:
  net_internal:
    external: true
    name: net_internal
