services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - ${OPS_ROOT:-../../../}/etc/global.env
      - ${OPS_ROOT:-../../../}/etc/srv/apps.vaultwarden.env
    volumes:
      - ${OPS_ROOT:-../../../}/lib/vaultwarden:/data
    networks: [net_internal]
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host(`${VAULT_HOST}`)
      - traefik.http.routers.vaultwarden.entrypoints=websecure
      - traefik.http.routers.vaultwarden.tls.certresolver=le-dns
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80

networks:
  net_internal:
    external: true
    name: net_internal
