services:
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    env_file:
      - ${OPS_ROOT:-../../../}/etc/global.env
      - ${OPS_ROOT:-../../../}/etc/srv/apps.registry.env
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - ${OPS_ROOT:-../../../}/lib/registry:/var/lib/registry
    networks: [net_internal]
    labels:
      - caddy=${REGISTRY_HOST}
      - caddy.reverse_proxy=registry:5000

networks:
  net_internal:
    external: true
    name: net_internal
