http:
  routers:
    unifi:
      rule: "Host(`unifi.home.mstorm.net`)"
      entryPoints:
        - websecure
      service: unifi
      tls: {}

  services:
    unifi:
      loadBalancer:
        servers:
          - url: "https://host.docker.internal:8443"
        serversTransport: unifi-transport

  serversTransports:
    unifi-transport:
      insecureSkipVerify: true
