services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    env_file:
      - ${OPS_ROOT:-.}/etc/global.env
      - ${OPS_ROOT:-.}/etc/srv/edge.cloudflared.env
    networks:
      - net_external

networks:
  net_external:
    external: true
    name: net_external
