services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    env_file:
      - ${OPS_ROOT:-../../../}/etc/global.env
      - ${OPS_ROOT:-../../../}/etc/srv/apps.gitea.env
    volumes:
      - ${OPS_ROOT:-../../../}/lib/gitea:/data
    networks: [net_internal]
    labels:
      - caddy=${GITEA_HOST}
      - caddy.reverse_proxy=gitea:3000

networks:
  net_internal:
    external: true
    name: net_internal
