services:
  unifi-db:
    image: mongo:4.4
    container_name: unifi-db
    restart: unless-stopped
    env_file:
      - ${OPS_ROOT:-../../../}/etc/global.env
      - ${OPS_ROOT:-../../../}/etc/srv/apps.unifi.env
    volumes:
      - ${OPS_ROOT:-../../../}/lib/unifi/db:/data/db
    networks:
      - net_internal
    ports:
      - "127.0.0.1:27017:27017"

  unifi:
    image: linuxserver/unifi-network-application:latest
    container_name: unifi
    restart: unless-stopped
    network_mode: host
    depends_on:
      - unifi-db
    env_file:
      - ${OPS_ROOT:-../../../}/etc/global.env
      - ${OPS_ROOT:-../../../}/etc/srv/apps.unifi.env
    volumes:
      - ${OPS_ROOT:-../../../}/lib/unifi:/config

networks:
  net_internal:
    external: true
    name: net_internal
