services:
  # [1] 데이터베이스
  unifi-db:
    image: mongo:4.4
    container_name: unifi-db
    restart: unless-stopped
    env_file:
      - ${OPS_ROOT:-../../../}/etc/global.env
      - ${OPS_ROOT:-../../../}/etc/srv/apps.unifi.env
    volumes:
      - ${OPS_ROOT:-../../../}/lib/unifi/db:/data/db
      - ${OPS_ROOT:-../../../}/srv/apps/unifi/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    networks:
      - net_internal
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # [2] UniFi 컨트롤러
  unifi-controller:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-controller
    restart: unless-stopped
    depends_on:
      unifi-db:
        condition: service_healthy
    env_file:
      - ${OPS_ROOT:-../../../}/etc/global.env
      - ${OPS_ROOT:-../../../}/etc/srv/apps.unifi.env
    environment:
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
    volumes:
      - ${OPS_ROOT:-../../../}/lib/unifi:/config
    ports:
      - "20443:8443"
      - "8080:8080"
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "1900:1900/udp"
      - "20843:8843"
      - "20880:8880"
      - "6789:6789"
      - "5514:5514/udp"
    networks:
      - net_internal
    labels:
      - traefik.enable=true
      - traefik.docker.network=net_internal
      - traefik.http.serversTransports.unifi.insecureSkipVerify=true
      - traefik.http.routers.unifi.rule=Host(`${UNIFI_HOST}`)
      - traefik.http.routers.unifi.entrypoints=websecure
      - traefik.http.routers.unifi.tls=true
      - traefik.http.services.unifi.loadbalancer.server.port=8443
      - traefik.http.services.unifi.loadbalancer.server.scheme=https
      - traefik.http.services.unifi.loadbalancer.server.transport=unifi@docker

networks:
  net_internal:
    external: true
    name: net_internal
