services:
  unifi-db:
    image: mongo:4.4
    container_name: unifi-db
    restart: unless-stopped
    env_file:
      - ${OPS_ROOT:-../../../}/etc/global.env
      - ${OPS_ROOT:-../../../}/etc/srv/apps.unifi-db.env
    volumes:
      - ${OPS_ROOT:-../../../}/lib/unifi-mongodb:/data/db
    network_mode: host
    command: mongod --bind_ip 127.0.0.1

  unifi:
    image: linuxserver/unifi-network-application:latest
    container_name: unifi
    restart: unless-stopped
    network_mode: host
    depends_on:
      - unifi-db
    env_file:
      - ${OPS_ROOT:-../../../}/etc/global.env
      - ${OPS_ROOT:-../../../}/etc/srv/apps.unifi.env
    volumes:
      - ${OPS_ROOT:-../../../}/lib/unifi:/config
