services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ${OPS_ROOT:-../../../}/lib/uptime-kuma:/app/data
    networks: [net_internal]
    labels:
      - caddy=uptime.home.mstorm.net
      - caddy.reverse_proxy=uptime-kuma:3001

networks:
  net_internal:
    external: true
    name: net_internal
