services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ${OPS_ROOT:-../../../}/lib/uptime-kuma:/app/data
    networks: [net_internal]
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.rule=Host(`uptime.home.mstorm.net`)
      - traefik.http.routers.uptime-kuma.entrypoints=websecure
      - traefik.http.routers.uptime-kuma.tls=true
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001

networks:
  net_internal:
    external: true
    name: net_internal
