services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    env_file:
      - ${OPS_ROOT:-../../../}/etc/global.env
      - ${OPS_ROOT:-../../../}/etc/srv/observability.grafana.env
    volumes:
      - ${OPS_ROOT:-../../../}/lib/grafana:/var/lib/grafana
      - ${OPS_ROOT:-../../../}/srv/observability/grafana/provisioning:/etc/grafana/provisioning:ro
    networks: [net_internal]
    labels:
      - caddy=grafana.home.mstorm.net
      - caddy.reverse_proxy=grafana:3000

networks:
  net_internal:
    external: true
    name: net_internal
