services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    env_file:
      - ${OPS_ROOT:-.}/etc/global.env
    volumes:
      - ${OPS_ROOT:-.}/lib/grafana:/var/lib/grafana
      - ${OPS_ROOT:-.}/srv/observability/grafana/provisioning:/etc/grafana/provisioning:ro
    networks: [net_internal]
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.home.${DNS_NAME:-home.internal}`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=le-dns
      - traefik.http.services.grafana.loadbalancer.server.port=3000

networks:
  net_internal:
    external: true
    name: net_internal
